### ISSUE TITLE
Pop-up gluggi við skráningu kt. umsjónarmanns

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#3]
þegar búið er að nýskrá kt. umsjónarmanns þá kemur pop-up gluggi þar sem segir
"String index out of range: -1"

**Comment by bluebottle** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1937)
        at com.idega.core.location.business.AddressBusinessBean.getUpdatedAddressByFullAddressString(AddressBusinessBean.java:345)
        at com.idega.user.business.UserBusinessBean.updateUsersMainAddressByFullAddressString(UserBusinessBean.java:3004)
        at is.idega.idegaweb.egov.company.business.CompanyApplicationBusinessBean.getUser(CompanyApplicationBusinessBean.java:1547)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by ingvarorn** [comment]
og nafn umsjónarmanns er ekki sótt

**Comment by idega** [comment]
Búinn að laga þetta. Kemur inn í næstu uppfærslu.

**Comment by ingvarorn** [comment]
var búið að laga þetta ? 
þegar ég slæ inn kennitölu í fyrsta skipti, þá birtist nafn OK
svo eyði ég út kennitölunni og slæ inn nýja, þá kemur þessi melding um index out of range ! virðist gerast þegar þarf að sækja í þjóðskrána, fæ ekki villu á kennitölu sem ég hef slegið inn e-n tímann áður

**Comment by idega** [comment]
Moved to clockingit
